import os
os = os.system
os("pkg update")
os("pkg upgrade")
os('pkg install figlet')
os("clear")
os("figlet -f slant Start")
os("pkg install python2")
os("pkg install ruby")
os("gem install lolcat")
os("figlet -f slant Complete | lolcat")
os("cd")
os("cd login-termux")
os("cp login.py /data/data/com.termux/files/home")
os("rm -rf /data/data/com.termux/files/usr/etc/bash.bashrc")
os("rm -rf /data/data/com.termux/files/usr/etc/motd")
os("cp -r bash.bashrc /data/data/com.termux/files/usr/etc")
print("\033[1;93m      Username     :     user")
print("\033[1;93m      Password     :     pass")
print("")
print("\033[1;91m>>>>>>>""\033[1;92m  Type python2 login.py")
print("")
print("\033[1;91m>>>>>>>""\033[1;92m  Restart Your Termux")
